apimservicename: rubicon-t-demo-apim
backends:  
   - name: azurenamingapp    
     properties:      
       url: "https://rubicon-t-namingapp-webapp.azurewebsites.net"
loggers:
   - name: appinsights
     properties:
       credentials:
         instrumentationKey": "{{application-insights-instrumentation-key}}"
       resourceId: "/subscriptions/29903316-1b21-45a9-9bcd-412cb865d18b/resourceGroups/rubicon-t-demo-apim/providers/Microsoft.Insights/components/rubicon-t-demo-appins"
diagnostics:
    - name: applicationinsights
      properties:
        loggerId: "/subscriptions/29903316-1b21-45a9-9bcd-412cb865d18b/resourceGroups/rubicon-t-demo-apim/providers/Microsoft.ApiManagement/service/rubicon-t-demo-apim/loggers/appinsights"
