apimservicename: rubicon-d-demo-apim
backends:  
   - name: azurenamingapp    
     properties:      
       url: "https://rubicon-d-namingapp-webapp.azurewebsites.net"
loggers:
   - name: rubicon-d-demo-appins
     properties:
       credentials:
         instrumentationKey": "{{application-insights-instrumentation-key}}"
       resourceId: "/subscriptions/29903316-1b21-45a9-9bcd-412cb865d18b/resourceGroups/rubicon-d-demo-apim/providers/Microsoft.Insights/components/rubicon-d-demo-appins"
